#!/bin/bash
# A simple script to make fzf a fuzzy-file explorer
# After the program exits, it should be cleared with tput rmcup, otherwise the
# terminal stays in alternate screen mode

OPTERR=0
while getopts ':o:' opt; do
  case "$opt" in
    o) output_dest="$OPTARG" ;;
  esac
done
shift $(( OPTIND - 1 ))
unset opt OPTARG OPTIND

if test -z $output_dest;then
    output_dest="/dev/stdout"
fi

fzf_bin="$HOME/src-repos/git-repos/fzf/target/fzf-linux_amd64"
fzf_tmp_buffer="$(mktemp -p /tmp fzf_buffer.XXXXXX)"
refresh_buffer=true
old_folder=$(pwd)
cur_folder="$old_folder"
tree_depth=1
id=0
fd_ignore=

tput smcup 1>&2
# cleanup and output result
function die() {
    tput rmcup 1>&2
    rm $fzf_tmp_buffer
    echo "$output" > "$output_dest"
    exit $code
}

trap die EXIT


while true
do
    # selection=$(test "$show_selection" && echo "$ret")
    { read query; read id; read key; read ret; read code; } <<< $(
        (test $refresh_buffer \
                && ( (echo -e '.'; fd -t d --color=always $fd_ignore) \
                    | tee "$fzf_tmp_buffer" ) \
                || cat "$fzf_tmp_buffer") \
            | ${fzf_bin} --height 100% --no-clear \
                --reverse \
                --print-sel-idx --sel-idx=$id \
                --print-query --query="$query" \
                --header="${cur_folder/#$HOME/'~'}" \
                --expect=ctrl-h,ctrl-l,ctrl-alt-m,ctrl-alt-h,ctrl-alt-l,alt-a \
                --expect=f1,f2,f3 \
                --preview-window=right:50% \
                --preview "tree -L $tree_depth -C {}"; \
        echo $?
        )
    refresh_buffer=
    case $code in
        130)
            output="$old_folder"
            break
            ;;
        0|1)
            case $key in
                ctrl-h)
                    cd ..
                    cur_folder=$(pwd)
                    query=''
                    refresh_buffer=true
                    ;;
                ctrl-l)
                    cd "$ret"
                    cur_folder=$(pwd)
                    query=''
                    refresh_buffer=true
                    ;;
                alt-enter|ctrl-alt-m)
                    output="$cur_folder"
                    break
                    ;;
                ctrl-alt-h)
                    tree_depth=$((tree_depth - 1 > 0 ? tree_depth - 1 : tree_depth))
                    ;;
                ctrl-alt-l)
                    tree_depth=$((tree_depth + 1))
                    ;;
                alt-a)
                    test -z $fd_ignore && fd_ignore="-HI" || fd_ignore=
                    refresh_buffer=true
                    ;;
                f1)
                    # some ingame help here
                    less << EOF
HELP

    * Shortcut:
        - ctrl-h/ctrl-l: go up/down the tree using the currently selected
          folder
        - ctrl-alt-h/ctrl-alt-l: expand/lower the depth of the tree view
        - alt-a: show/hide hidden directory
        - f1: show this help
        - f2: start your terminal image viewer, imgp
        - f3: start your text file previewer, nvrp

        - alt-enter/wtrl-alt-m: output current folder and exit
        - enter: output folder under cursor and exit
        - escape: exit with no output
EOF
                    ;;
                f2)
                    # custom script to see image in terminal
                    imgp --no-clear
                    ;;
                f3)
                    # custom script to open file in remote neovim session
                    nvrp --no-clear
                    ;;
                *)
                    cd "$ret"
                    output=$(pwd)
                    break
                    ;;
            esac
            ;;
        *)
            output="$old_folder"
            break;
            ;;
    esac
done

