#!/bin/bash
# A simple script to make fzf a fuzzy-file explorer
# After the program exits, it should be cleared with tput rmcup, otherwise the
# terminal stays in alternate screen mode

fzf_bin="$HOME/src-repos/git-repos/fzf/target/fzf-linux_amd64"
fzf_tmp_buffer="$(mktemp -p /tmp fzf_buffer.XXXXXX)"
refresh_buffer=true
old_folder=$(pwd)
cur_folder="$old_folder"
tree_depth=1
id=0
while true
do
    # selection=$(test "$show_selection" && echo "$ret")
    { read query; read id; read key; read ret; read code; } <<< $(
        (test $refresh_buffer \
                && ( (echo -e '.'; fd -t d --color=always) \
                    | tee "$fzf_tmp_buffer" ) \
                || cat "$fzf_tmp_buffer") \
            | ${fzf_bin} --height 100% --no-clear \
                --reverse \
                --print-sel-idx --sel-idx=$id \
                --print-query --query="$query" \
                --header="${cur_folder/#$HOME/'~'} $query" \
                --expect=ctrl-h,ctrl-l,ctrl-alt-m,ctrl-alt-h,ctrl-alt-l \
                --expect=f1,f2,f3 \
                --preview-window=right:50% \
                --preview "tree -L $tree_depth -C {}"; \
        echo $?
        )
    refresh_buffer=
    case $code in
        130)
            output="$old_folder"
            break
            ;;
        0|1)
            case $key in
                ctrl-h)
                    cd ..
                    cur_folder=$(pwd)
                    query=''
                    refresh_buffer=true
                    ;;
                ctrl-l)
                    cd "$ret"
                    cur_folder=$(pwd)
                    query=''
                    refresh_buffer=true
                    ;;
                alt-enter|ctrl-alt-m)
                    output="$cur_folder"
                    break
                    ;;
                ctrl-alt-h)
                    tree_depth=$((tree_depth - 1 > 0 ? tree_depth - 1 : tree_depth))
                    ;;
                ctrl-alt-l)
                    tree_depth=$((tree_depth + 1))
                    ;;
                f1)
                    # some ingame help here
                    ;;
                f2)
                    # custom script to see image in terminal
                    imgp --no-clear
                    ;;
                f3)
                    # custom script to open file in remote neovim session
                    nvrp --no-clear
                    ;;
                *)
                    cd "$ret"
                    output=$(pwd)
                    break
                    ;;
            esac
            ;;
        *)
            output="$old_folder"
            break;
            ;;
    esac
done

rm "$fzf_tmp_buffer"
echo $output
exit $code
